### PR TITLE
replace web3connect w/ web3modal and some npm update

### PR DESCRIPTION
**Pull request by Aragar199**
* web3connect was rebranded and deprecated according to https://www.npmjs.com/package/web3connect
* followed migration instructions to web3modal
* also ran npm update to do safe version update

### CODE REVIEW

**Comment by grahamtallen** [comment]
@Aragar199 I need to rewatch some eth.build videos...How do you you test this locally, making sure these web3 functions work?

**Comment by Aragar199** [comment]
@grahamtallen you can test using the save and load buttons in the bottom menu bar. Should be in SaveDialog.js and LoadDialog.js using your metamask.

**Comment by grahamtallen** [comment]
Works perfect on Chrome. I see there is already a different issue opened up for saving on FF. ✅

**Comment by grahamtallen** [comment]
Deployed to sandbox.eth.build! Thank you @Aragar199 !

**Pull request merged**
